# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c612e1af808a24d6d4ee4606576f3240df43ef133d196a97b350889bfd3ee6d8a9ad7639f60592d01595b3a94261dc948859991b4b3ea5fa418f91366dc7b201

test:
  secret_key_base: 82150f7b30e331dfa9589da0e7cdd81da00d8ebcae31037d34f7691e33a93d31529e84a20108aada4a86e053d0e2d6ca2a26484dcc4f8c72ef3666d01130641f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
